version: '3'

services:

  twitter_bot:
    image: jahrik/bot:latest
    environment:
      - TWITTER_KEY=${TWITTER_KEY}
      - TWITTER_SECRET=${TWITTER_SECRET}
      - TWITTER_TOKEN=${TWITTER_TOKEN}
      - TWITTER_TOKEN_SECRET=${TWITTER_TOKEN_SECRET}
    depends_on:
      - mongo
    command: python3 edward.py -b twitter

  hipchat_bot:
    image: jahrik/bot:latest
    environment:
      - HIPCHAT_HOST=${HIPCHAT_HOST}
      - HIPCHAT_ROOM=${HIPCHAT_ROOM}
      - HIPCHAT_ACCESS_TOKEN=${HIPCHAT_ACCESS_TOKEN}
    depends_on:
      - mongo
    command: python3 edward.py -b hipchat

  gitter_bot:
    image: jahrik/bot:latest
    environment:
      - GITTER_ROOM=${GITTER_ROOM}
      - GITTER_API_TOKEN=${GITTER_API_TOKEN}
    depends_on:
      - mongo
    command: python3 edward.py -b gitter

  mongo:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      # - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod
